version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: ./packages/webapp/Dockerfile
    ports:
      - '4000:80'
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - '8000:3000'
